/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.9.0 on Fri Apr 29 19:54:18 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_hw3_h_)
#define _hw3_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief accelerometer identifiers */
enum _accelerometer_ids
{
    kaccelerometer_service_id = 1,
    kaccelerometer_service_on_id = 1,
    kaccelerometer_service_off_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name accelerometer
//@{
void service_on(void);

void service_off(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _hw3_h_
