# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Fri Apr 29 20:46:04 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for accelerometer
class Iaccelerometer(object):
    SERVICE_ID = 1
    SERVICE_ON_ID = 1
    SERVICE_OFF_ID = 2

    def service_on(self):
        raise NotImplementedError()

    def service_off(self):
        raise NotImplementedError()


