# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Fri Apr 29 20:46:04 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for accelerometer
class accelerometerService(erpc.server.Service):
    def __init__(self, handler):
        super(accelerometerService, self).__init__(interface.Iaccelerometer.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.Iaccelerometer.SERVICE_ON_ID: self._handle_service_on,
                interface.Iaccelerometer.SERVICE_OFF_ID: self._handle_service_off,
            }

    def _handle_service_on(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        self._handler.service_on()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.Iaccelerometer.SERVICE_ID,
            request=interface.Iaccelerometer.SERVICE_ON_ID,
            sequence=sequence))

    def _handle_service_off(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        self._handler.service_off()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.Iaccelerometer.SERVICE_ID,
            request=interface.Iaccelerometer.SERVICE_OFF_ID,
            sequence=sequence))


